version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: artifactor_postgres
    environment:
      POSTGRES_DB: artifactor_v3
      POSTGRES_USER: artifactor
      POSTGRES_PASSWORD: artifactor
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - artifactor_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artifactor -d artifactor_v3"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: artifactor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - artifactor_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: artifactor_backend
    environment:
      - DATABASE_URL=postgresql://artifactor:artifactor@postgres:5432/artifactor_v3
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ../backend:/app
      - upload_data:/app/uploads
    ports:
      - "8000:8000"
    networks:
      - artifactor_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: artifactor_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - artifactor_network
    depends_on:
      - backend
    restart: unless-stopped
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: artifactor_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - upload_data:/var/www/uploads
    ports:
      - "80:80"
      - "443:443"
    networks:
      - artifactor_network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    profiles:
      - production

  # Agent Bridge Service (v2.0 compatibility)
  agent_bridge:
    build:
      context: ../backend
      dockerfile: Dockerfile.agent_bridge
    container_name: artifactor_agent_bridge
    environment:
      - DATABASE_URL=postgresql://artifactor:artifactor@postgres:5432/artifactor_v3
      - V2_COMPATIBILITY=true
      - AGENT_COORDINATION_ENABLED=true
    volumes:
      - ../backend:/app
      - agent_bridge_data:/app/agent_data
      - ../:/home/john/ARTIFACTOR  # Mount v2.0 directory for compatibility
    networks:
      - artifactor_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - full

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  upload_data:
    driver: local
  agent_bridge_data:
    driver: local

networks:
  artifactor_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16