apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactor-backend
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactor-frontend
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  replicas: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: artifactor-backend-hpa
spec:
  minReplicas: 2
  maxReplicas: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: artifactor-frontend-hpa
spec:
  minReplicas: 2
  maxReplicas: 8