apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifactor

resources:
- ../base

patchesStrategicMerge:
- replica-count.yml
- resource-limits.yml
- storage-config.yml
- security-config.yml

configMapGenerator:
- name: production-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO
  - DEBUG=false
  - API_WORKERS=8
  - REDIS_MAX_CONNECTIONS=2000
  - DB_POOL_SIZE=20
  - WS_MAX_CONNECTIONS=5000

secretGenerator:
- name: production-secrets
  literals:
  - POSTGRES_PASSWORD=production-password-change-me
  - REDIS_PASSWORD=production-redis-password
  - SECRET_KEY=production-secret-key-change-me
  - GRAFANA_PASSWORD=production-grafana-password
  - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
  - S3_BACKUP_BUCKET=artifactor-production-backups
  - AWS_ACCESS_KEY_ID=your-aws-access-key
  - AWS_SECRET_ACCESS_KEY=your-aws-secret-key
  - GITHUB_CLIENT_SECRET=your-github-oauth-secret
  - OPENAI_API_KEY=your-openai-api-key
  - CLAUDE_API_KEY=your-claude-api-key

images:
- name: ghcr.io/artifactor/backend
  newTag: production
- name: ghcr.io/artifactor/frontend
  newTag: production
- name: ghcr.io/artifactor/nginx
  newTag: production

commonLabels:
  environment: production
  version: v3.0