apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactor-frontend
  namespace: artifactor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artifactor-frontend
  template:
    metadata:
      labels:
        app: artifactor-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/artifactor/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "https://api.artifactor.app"
        - name: REACT_APP_WS_URL
          value: "wss://api.artifactor.app/ws"
        - name: REACT_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: artifactor-config
              key: APP_VERSION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        node-type: frontend
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - artifactor-frontend
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: artifactor-frontend-service
  namespace: artifactor
spec:
  selector:
    app: artifactor-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: artifactor-frontend-hpa
  namespace: artifactor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: artifactor-frontend
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 30
        periodSeconds: 60